# Generated by Django 4.1.1 on 2022-12-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="ID",
        ),
    ]
