# Generated by Django 4.1.1 on 2022-12-24 14:12

from django.db import migrations, models
import django.db.models.deletion
import locations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("address", models.CharField(max_length=500, unique=True)),
                ("description", models.CharField(max_length=1500)),
                (
                    "images",
                    models.ImageField(upload_to=locations.models.image_directory_path),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
