# Generated by Django 4.1.1 on 2022-12-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
